version: '3.1'

services:

  motion:
    container_name: driveway-motion
    image: jritsema/rpi-motion-mmal
    devices:
      - "/dev/vchiq"
    volumes:
      - /home/pi/motion:/home/pi
      - /home/pi/cam-driveway/motion-mmalcam.conf:/etc/motion.conf
    ports:
      - "80:8081"
      - "8080:8080"
    restart: always
